name: Deploy To Azure from IaC

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for the Deployment'
        required: true

jobs:
  deploy:
    name: Deploy Bicep Template
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure using a Service Principal
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy Bicep template
        run: |
          # Install Azure CLI if not already installed
          if ! command -v az &> /dev/null
          then
              echo "Azure CLI not found, installing..."
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi

          # Deploy the Bicep template
          az deployment sub create --name IaC-Demo --location eastus --template-file ./infra/main.bicep --parameters enablePublicIp=false --parameters username='${{ inputs.username }}'
